### ISSUE TITLE
Layout cannot changes?

### ISSUE THREAD

**Issue by kireniusdena** [dektrium/yii2-user-demo#6]
I have something layout
for admin and for login

My setting module is 

> 'user' => [
            'class' => 'dektrium\user\Module',
            'enableUnconfirmedLogin' => true,
            'confirmWithin' => 21600,
            'cost' => 12,
            'admins' => ['kireniusdena'],
            'mailer' => [
                'sender'                => 'local-server@local-server.link', // or ['no-reply@myhost.com' => 'Sender name']
                'welcomeSubject'        => 'Welcome subject',
                'confirmationSubject'   => 'Confirmation subject',
                'reconfirmationSubject' => 'Email change subject',
                'recoverySubject'       => 'Recovery subject',
            ],
            'controllerMap' => [
                'admin' => [
                  'class' => 'dektrium\user\controllers\AdminController',
                  'layout' => '@app/modules/administrator/views/layouts/main',
                ],
                'login' => [
                  'class' => 'dektrium\user\controllers\LoginController',
                  'layout' => '@app/modules/administrator/views/layouts/main',
                ],
            ],
        ],

how to fix this? thx you

**Comment by dmeroff** [comment]
https://github.com/dektrium/yii2-user/issues/646#issuecomment-202086578
